version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
     - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
     - "./web:/var/www/html/public"
    ports:
     - "8000:80"
    environment:
     - NGINX_HOST=localhost
    restart: always

