version: '3'
services:
  web:
    image: nginx:alpine
    volumes:
     - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
     - "./web:/var/www/html/public"
    ports:
     - "8000:80"
    environment:
     - NGINX_HOST=localhost
    restart: always
    depends_on:
     - php
     - mysql

  php:
    image: php:7.2.2-fpm-alpine3.7
    restart: always
    volumes:
     - "./web:/var/www/html/public"

  mysql:
    image: mariadb:latest
    restart: always 
    environment:
     - MYSQL_DATABASE='dockertest'
     - MYSQL_ROOT_PASSWORD='password'
     - MYSQL_USER='user'
     - MYSQL_PASSWORD='drowssap'
    volumes:
     - "./data/db/mysql:/var/lib/mysql"
